import type { Event } from '@/lib/types';

export const DUMMY_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Indie Music Fest',
    description:
      'Join us for a weekend of incredible live music from the best indie bands around the world. Food trucks, art installations, and good vibes guaranteed. The event runs for two full days, so grab your tickets now!',
    date: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    location: 'Mumbai, Maharashtra',
    imageUrl: 'https://picsum.photos/seed/1/600/400',
    imageHint: 'music concert',
    organizer: {
      name: 'Vibe Creators',
      avatarUrl: 'https://picsum.photos/seed/101/40/40',
    },
    category: 'Music',
    status: 'published',
  },
  {
    id: '2',
    title: 'Modern Art Showcase',
    description:
      'Explore the cutting edge of contemporary art. This exhibition features works from over 50 emerging artists. A must-see for art lovers and collectors. The showcase is open for a month, with special curator talks on weekends.',
    date: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString(),
    location: 'Delhi, NCT',
    imageUrl: 'https://picsum.photos/seed/2/600/400',
    imageHint: 'art gallery',
    organizer: {
      name: 'Canvas Collective',
      avatarUrl: 'https://picsum.photos/seed/102/40/40',
    },
    category: 'Art',
    status: 'published',
  },
  {
    id: '3',
    title: 'Global Food Festival',
    description:
      "Taste the world in one place! Our annual food festival brings together cuisines from every corner of the globe. A paradise for foodies, with cooking demos and live entertainment. Don't miss this delicious experience.",
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    location: 'Bangalore, Karnataka',
    imageUrl: 'https://picsum.photos/seed/3/600/400',
    imageHint: 'food festival',
    organizer: {
      name: 'Gourmet Gatherings',
      avatarUrl: 'https://picsum.photos/seed/103/40/40',
    },
    category: 'Food',
    status: 'draft',
  },
  {
    id: '4',
    title: 'Future of Tech Summit',
    description:
      'A two-day conference on the future of technology. Hear from industry leaders on AI, blockchain, and more. Network with innovators and get a glimpse into tomorrow. Limited seats available.',
    date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    location: 'Hyderabad, Telangana',
    imageUrl: 'https://picsum.photos/seed/4/600/400',
    imageHint: 'tech conference',
    organizer: {
      name: 'Innovate Hub',
      avatarUrl: 'https://picsum.photos/seed/104/40/40',
    },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '5',
    title: 'City Marathon 2024',
    description:
      'Join thousands of runners for the annual city marathon. A scenic route through the heart of the city. Open to all fitness levels, with 5K, 10K, and full marathon categories. Register now and be part of the excitement.',
    date: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    location: 'Chennai, Tamil Nadu',
    imageUrl: 'https://picsum.photos/seed/5/600/400',
    imageHint: 'marathon run',
    organizer: {
      name: 'RunFit',
      avatarUrl: 'https://picsum.photos/seed/105/40/40',
    },
    category: 'Sports',
    status: 'published',
  },
  {
    id: '6',
    title: 'Organic Farmers Market',
    description:
      'Get your weekly stock of fresh, organic produce directly from local farmers. Vegetables, fruits, honey, and more. Support local and eat healthy. Every Sunday for the next month.',
    date: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    location: 'Pune, Maharashtra',
    imageUrl: 'https://picsum.photos/seed/6/600/400',
    imageHint: 'farmers market',
    organizer: {
      name: 'Green Roots',
      avatarUrl: 'https://picsum.photos/seed/106/40/40',
    },
    category: 'Community',
    status: 'draft',
  },
  {
    id: '7',
    title: 'Sunrise Yoga Workshop',
    description:
      'Start your day with a rejuvenating yoga session in the park. This workshop is suitable for all levels, focusing on mindfulness and breathing techniques. A perfect way to connect with nature and yourself.',
    date: new Date(new Date().setDate(new Date().getDate() + 9)).toISOString(),
    location: 'Kolkata, West Bengal',
    imageUrl: 'https://picsum.photos/seed/7/600/400',
    imageHint: 'yoga workshop',
    organizer: {
      name: 'Zen Space',
      avatarUrl: 'https://picsum.photos/seed/107/40/40',
    },
    category: 'Wellness',
    status: 'published',
  },
  {
    id: '8',
    title: 'Annual Book Fair',
    description:
      'A celebration of literature and reading. Discover new authors, find rare editions, and enjoy talks from your favorite writers. A haven for book lovers of all ages, running for 10 days.',
    date: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString(),
    location: 'Jaipur, Rajasthan',
    imageUrl: 'https://picsum.photos/seed/8/600/400',
    imageHint: 'book fair',
    organizer: {
      name: 'Readers Guild',
      avatarUrl: 'https://picsum.photos/seed/108/40/40',
    },
    category: 'Literature',
    status: 'published',
  },
  {
    id: '9',
    title: 'Himalayan Trekking Expedition',
    description:
      'Embark on a breathtaking trekking adventure in the Himalayas. This guided tour is perfect for experienced trekkers looking for a challenge. All equipment and meals provided.',
    date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(),
    location: 'Shimla, Himachal Pradesh',
    imageUrl: 'https://picsum.photos/seed/9/600/400',
    imageHint: 'mountain trek',
    organizer: {
      name: 'Mountain Escapes',
      avatarUrl: 'https://picsum.photos/seed/109/40/40',
    },
    category: 'Adventure',
    status: 'published',
  },
  {
    id: '10',
    title: 'Classical Dance Festival',
    description:
      'Experience the rich cultural heritage of India through classical dance. Featuring performances of Bharatanatyam, Kathak, and Odissi by renowned artists.',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    location: 'Bhubaneswar, Odisha',
    imageUrl: 'https://picsum.photos/seed/10/600/400',
    imageHint: 'classical dance',
    organizer: {
      name: 'Nritya Academy',
      avatarUrl: 'https://picsum.photos/seed/110/40/40',
    },
    category: 'Art',
    status: 'published',
  },
  {
    id: '11',
    title: 'Startup Pitch Night',
    description:
      'Watch the next generation of entrepreneurs pitch their innovative ideas to a panel of investors. A great networking opportunity for startups and investors alike.',
    date: new Date(new Date().setDate(new Date().getDate() + 11)).toISOString(),
    location: 'Gurugram, Haryana',
    imageUrl: 'https://picsum.photos/seed/11/600/400',
    imageHint: 'business meeting',
    organizer: {
      name: 'Venture Catalysts',
      avatarUrl: 'https://picsum.photos/seed/111/40/40',
    },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '12',
    title: 'Goa Beach Cleanup',
    description:
      "Join us in making a difference! Spend a morning with fellow volunteers cleaning up one of Goa's beautiful beaches. A rewarding experience for a great cause.",
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    location: 'Panaji, Goa',
    imageUrl: 'https://picsum.photos/seed/12/600/400',
    imageHint: 'beach cleanup',
    organizer: {
      name: 'Ocean Guardians',
      avatarUrl: 'https://picsum.photos/seed/112/40/40',
    },
    category: 'Community',
    status: 'draft',
  },
  {
    id: '13',
    title: 'Street Food Tour',
    description:
      'Explore the vibrant street food scene of Ahmedabad. A guided tour to taste the most authentic and delicious local delicacies. Come with an empty stomach!',
    date: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    location: 'Ahmedabad, Gujarat',
    imageUrl: 'https://picsum.photos/seed/13/600/400',
    imageHint: 'street food',
    organizer: {
      name: 'Foodie Trails',
      avatarUrl: 'https://picsum.photos/seed/113/40/40',
    },
    category: 'Food',
    status: 'published',
  },
  {
    id: '14',
    title: 'Photography Walk',
    description:
      'Capture the architectural beauty and bustling street life of old Lucknow. A guided walk for photography enthusiasts of all skill levels.',
    date: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    location: 'Lucknow, Uttar Pradesh',
    imageUrl: 'https://picsum.photos/seed/14/600/400',
    imageHint: 'city photography',
    organizer: {
      name: 'Shutterbugs United',
      avatarUrl: 'https://picsum.photos/seed/114/40/40',
    },
    category: 'Art',
    status: 'published',
  },
  {
    id: '15',
    title: 'Meditation and Mindfulness Retreat',
    description:
      'A weekend retreat to disconnect from the hustle and bustle. Guided meditation sessions, mindfulness practices, and serene natural surroundings to help you relax and rejuvenate.',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    location: 'Rishikesh, Uttarakhand',
    imageUrl: 'https://picsum.photos/seed/15/600/400',
    imageHint: 'meditation retreat',
    organizer: {
      name: 'Inner Peace Foundation',
      avatarUrl: 'https://picsum.photos/seed/115/40/40',
    },
    category: 'Wellness',
    status: 'published',
  },
  {
    id: '16',
    title: 'Rock Climbing Workshop',
    description:
      'Learn the basics of rock climbing from certified instructors at this hands-on workshop. All safety equipment will be provided. Perfect for beginners and adrenaline junkies.',
    date: new Date(new Date().setDate(new Date().getDate() + 22)).toISOString(),
    location: 'Hampi, Karnataka',
    imageUrl: 'https://picsum.photos/seed/16/600/400',
    imageHint: 'rock climbing',
    organizer: {
      name: 'Climb On',
      avatarUrl: 'https://picsum.photos/seed/116/40/40',
    },
    category: 'Sports',
    status: 'published',
  },
  {
    id: '17',
    title: 'Sufi Music Night',
    description:
      'Experience an evening of soulful Sufi music under the stars. Featuring renowned qawwali singers in a magical setting.',
    date: new Date(new Date().setDate(new Date().getDate() + 19)).toISOString(),
    location: 'Ajmer, Rajasthan',
    imageUrl: 'https://picsum.photos/seed/17/600/400',
    imageHint: 'sufi music',
    organizer: {
      name: 'Ruhaniyat',
      avatarUrl: 'https://picsum.photos/seed/117/40/40',
    },
    category: 'Music',
    status: 'published',
  },
  {
    id: '18',
    title: 'AI and Machine Learning Bootcamp',
    description:
      'An intensive 3-day bootcamp covering the fundamentals of AI and Machine Learning. Hands-on coding sessions and projects. Certificate of completion provided.',
    date: new Date(new Date().setDate(new Date().getDate() + 28)).toISOString(),
    location: 'Indore, Madhya Pradesh',
    imageUrl: 'https://picsum.photos/seed/18/600/400',
    imageHint: 'coding bootcamp',
    organizer: {
      name: 'Data Minds',
      avatarUrl: 'https://picsum.photos/seed/118/40/40',
    },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '19',
    title: 'Poetry Slam Competition',
    description:
      'A platform for poets to share their work and compete for the title of Slam Champion. An evening of powerful words and emotions.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    location: 'Chandigarh, Punjab',
    imageUrl: 'https://picsum.photos/seed/19/600/400',
    imageHint: 'poetry reading',
    organizer: {
      name: 'Word Weavers',
      avatarUrl: 'https://picsum.photos/seed/119/40/40',
    },
    category: 'Literature',
    status: 'published',
  },
  {
    id: '20',
    title: 'Backwaters Houseboat Cruise',
    description:
      'A relaxing day cruise through the serene backwaters of Kerala on a traditional houseboat. Includes authentic Keralan lunch.',
    date: new Date(new Date().setDate(new Date().getDate() + 24)).toISOString(),
    location: 'Alappuzha, Kerala',
    imageUrl: 'https://picsum.photos/seed/20/600/400',
    imageHint: 'houseboat cruise',
    organizer: {
      name: 'Kerala Escapes',
      avatarUrl: 'https://picsum.photos/seed/120/40/40',
    },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '21',
    title: 'Kathakali Performance Night',
    description: 'Witness the traditional dance-drama of Kerala. An unforgettable cultural experience.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    location: 'Thrissur, Kerala',
    imageUrl: 'https://picsum.photos/seed/21/600/400',
    imageHint: 'kathakali dance',
    organizer: { name: 'Kala Kendra', avatarUrl: 'https://picsum.photos/seed/121/40/40' },
    category: 'Art',
    status: 'published',
  },
  {
    id: '22',
    title: 'Kochi-Muziris Biennale Tour',
    description: 'A guided tour of the largest contemporary art exhibition in India.',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    location: 'Ernakulam, Kerala',
    imageUrl: 'https://picsum.photos/seed/22/600/400',
    imageHint: 'art biennale',
    organizer: { name: 'Art Connect', avatarUrl: 'https://picsum.photos/seed/122/40/40' },
    category: 'Art',
    status: 'published',
  },
  {
    id: '23',
    title: 'Malabar Food Festival',
    description: 'Savor the unique flavors of Malabar cuisine, from biryanis to seafood delicacies.',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    location: 'Kozhikode, Kerala',
    imageUrl: 'https://picsum.photos/seed/23/600/400',
    imageHint: 'food festival',
    organizer: { name: 'Taste of Malabar', avatarUrl: 'https://picsum.photos/seed/123/40/40' },
    category: 'Food',
    status: 'published',
  },
  {
    id: '24',
    title: 'Theyyam Ritual Performance',
    description: 'Experience the ancient and vibrant ritual art form of North Kerala.',
    date: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString(),
    location: 'Kannur, Kerala',
    imageUrl: 'https://picsum.photos/seed/24/600/400',
    imageHint: 'theyyam ritual',
    organizer: { name: 'Kannur Heritage', avatarUrl: 'https://picsum.photos/seed/124/40/40' },
    category: 'Community',
    status: 'published',
  },
  {
    id: '25',
    title: 'Wayanad Tea Plantation Visit',
    description: 'A guided tour through the lush green tea gardens of Wayanad, including a tea tasting session.',
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    location: 'Wayanad, Kerala',
    imageUrl: 'https://picsum.photos/seed/25/600/400',
    imageHint: 'tea plantation',
    organizer: { name: 'Wayanad Trails', avatarUrl: 'https://picsum.photos/seed/125/40/40' },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '26',
    title: 'Kerala Blockchain Summit',
    description: 'A conference exploring the future of blockchain technology and its applications in Kerala.',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    location: 'Thiruvananthapuram, Kerala',
    imageUrl: 'https://picsum.photos/seed/26/600/400',
    imageHint: 'tech summit',
    organizer: { name: 'Tech Trivandrum', avatarUrl: 'https://picsum.photos/seed/126/40/40' },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '27',
    title: 'Snake Boat Race on Ashtamudi Lake',
    description: 'Witness the thrilling traditional snake boat races of Kerala.',
    date: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString(),
    location: 'Kollam, Kerala',
    imageUrl: 'https://picsum.photos/seed/27/600/400',
    imageHint: 'boat race',
    organizer: { name: 'Kollam Sports Council', avatarUrl: 'https://picsum.photos/seed/127/40/40' },
    category: 'Sports',
    status: 'published',
  },
  {
    id: '28',
    title: 'Ayurveda & Wellness Retreat',
    description: 'A 5-day retreat focusing on traditional Ayurvedic treatments and yoga.',
    date: new Date(new Date().setDate(new Date().getDate() + 45)).toISOString(),
    location: 'Palakkad, Kerala',
    imageUrl: 'https://picsum.photos/seed/28/600/400',
    imageHint: 'wellness retreat',
    organizer: { name: 'Shanti Ayurveda', avatarUrl: 'https://picsum.photos/seed/128/40/40' },
    category: 'Wellness',
    status: 'published',
  },
  {
    id: '29',
    title: 'Kottayam Literary Festival',
    description: 'A celebration of literature with talks by prominent authors and poets.',
    date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    location: 'Kottayam, Kerala',
    imageUrl: 'https://picsum.photos/seed/29/600/400',
    imageHint: 'literary festival',
    organizer: { name: 'Aksharam', avatarUrl: 'https://picsum.photos/seed/129/40/40' },
    category: 'Literature',
    status: 'published',
  },
  {
    id: '30',
    title: 'Periyar Wildlife Sanctuary Trek',
    description: 'A guided trek through one of India\'s most famous wildlife sanctuaries.',
    date: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    location: 'Idukki, Kerala',
    imageUrl: 'https://picsum.photos/seed/30/600/400',
    imageHint: 'wildlife trek',
    organizer: { name: 'Jungle Journeys', avatarUrl: 'https://picsum.photos/seed/130/40/40' },
    category: 'Adventure',
    status: 'published',
  },
  {
    id: '31',
    title: 'Bekal Fort Exploration Day',
    description: 'Explore the history and architecture of the magnificent Bekal Fort.',
    date: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    location: 'Kasaragod, Kerala',
    imageUrl: 'https://picsum.photos/seed/31/600/400',
    imageHint: 'fort exploration',
    organizer: { name: 'Kasaragod Tourism', avatarUrl: 'https://picsum.photos/seed/131/40/40' },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '32',
    title: 'Bamboo Rafting in Pathanamthitta',
    description: 'An adventurous bamboo rafting experience on the rivers of Pathanamthitta.',
    date: new Date(new Date().setDate(new Date().getDate() + 22)).toISOString(),
    location: 'Pathanamthitta, Kerala',
    imageUrl: 'https://picsum.photos/seed/32/600/400',
    imageHint: 'bamboo rafting',
    organizer: { name: 'River Adventures', avatarUrl: 'https://picsum.photos/seed/132/40/40' },
    category: 'Adventure',
    status: 'published',
  },
  {
    id: '33',
    title: 'Chettikulangara Bharani Festival',
    description: 'Experience one of Kerala\'s most colourful temple festivals with grand processions.',
    date: new Date(new Date().setDate(new Date().getDate() + 9)).toISOString(),
    location: 'Alappuzha, Kerala',
    imageUrl: 'https://picsum.photos/seed/33/600/400',
    imageHint: 'temple festival',
    organizer: { name: 'Festival Committee', avatarUrl: 'https://picsum.photos/seed/133/40/40' },
    category: 'Community',
    status: 'published',
  },
  {
    id: '34',
    title: 'Kerala Sadya Cooking Class',
    description: 'Learn to cook the traditional multi-course vegetarian feast of Kerala.',
    date: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    location: 'Ernakulam, Kerala',
    imageUrl: 'https://picsum.photos/seed/34/600/400',
    imageHint: 'cooking class',
    organizer: { name: 'Saras Kitchen', avatarUrl: 'https://picsum.photos/seed/134/40/40' },
    category: 'Food',
    status: 'published',
  },
  {
    id: '35',
    title: 'Mappila Music Concert',
    description: 'An evening of traditional Mappila Pattu, a folklore Muslim song genre.',
    date: new Date(new Date().setDate(new Date().getDate() + 11)).toISOString(),
    location: 'Malappuram, Kerala',
    imageUrl: 'https://picsum.photos/seed/35/600/400',
    imageHint: 'music concert',
    organizer: { name: 'Malappuram Arts', avatarUrl: 'https://picsum.photos/seed/135/40/40' },
    category: 'Music',
    status: 'published',
  },
  {
    id: '36',
    title: 'Poovar Island Backwater Cruise',
    description: 'A serene cruise through the untouched backwaters of Poovar.',
    date: new Date(new Date().setDate(new Date().getDate() + 4)).toISOString(),
    location: 'Thiruvananthapuram, Kerala',
    imageUrl: 'https://picsum.photos/seed/36/600/400',
    imageHint: 'backwater cruise',
    organizer: { name: 'Poovar Boating', avatarUrl: 'https://picsum.photos/seed/136/40/40' },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '37',
    title: 'Thrissur Pooram Exhibition',
    description: 'A grand exhibition showcasing the cultural elements of Thrissur Pooram.',
    date: new Date(new Date().setDate(new Date().getDate() + 16)).toISOString(),
    location: 'Thrissur, Kerala',
    imageUrl: 'https://picsum.photos/seed/37/600/400',
    imageHint: 'cultural exhibition',
    organizer: { name: 'Pooram Committee', avatarUrl: 'https://picsum.photos/seed/137/40/40' },
    category: 'Community',
    status: 'published',
  },
  {
    id: '38',
    title: 'Kalaripayattu Workshop',
    description: 'Learn the basics of the ancient martial art form of Kerala.',
    date: new Date(new Date().setDate(new Date().getDate() + 21)).toISOString(),
    location: 'Kozhikode, Kerala',
    imageUrl: 'https://picsum.photos/seed/38/600/400',
    imageHint: 'martial arts',
    organizer: { name: 'Kalari Gurukulam', avatarUrl: 'https://picsum.photos/seed/138/40/40' },
    category: 'Sports',
    status: 'published',
  },
  {
    id: '39',
    title: 'Theyyam Photography Tour',
    description: 'A specialized tour for photographers to capture the vibrant Theyyam performances.',
    date: new Date(new Date().setDate(new Date().getDate() + 26)).toISOString(),
    location: 'Kannur, Kerala',
    imageUrl: 'https://picsum.photos/seed/39/600/400',
    imageHint: 'photography tour',
    organizer: { name: 'Capture Kerala', avatarUrl: 'https://picsum.photos/seed/139/40/40' },
    category: 'Art',
    status: 'published',
  },
  {
    id: '40',
    title: 'Munnar Spice Garden Tour',
    description: 'A fragrant tour of a spice garden in Munnar, learning about various spices.',
    date: new Date(new Date().setDate(new Date().getDate() + 13)).toISOString(),
    location: 'Idukki, Kerala',
    imageUrl: 'https://picsum.photos/seed/40/600/400',
    imageHint: 'spice garden',
    organizer: { name: 'Munnar Spice Co.', avatarUrl: 'https://picsum.photos/seed/140/40/40' },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '41',
    title: 'Vagamon Paragliding Festival',
    description: 'Experience the thrill of paragliding over the beautiful hills of Vagamon.',
    date: new Date(new Date().setDate(new Date().getDate() + 35)).toISOString(),
    location: 'Kottayam, Kerala',
    imageUrl: 'https://picsum.photos/seed/41/600/400',
    imageHint: 'paragliding festival',
    organizer: { name: 'Fly Vagamon', avatarUrl: 'https://picsum.photos/seed/141/40/40' },
    category: 'Adventure',
    status: 'published',
  },
  {
    id: '42',
    title: 'Kerala IT Conclave 2024',
    description: 'The biggest IT conclave in Kerala, focusing on new-age technologies.',
    date: new Date(new Date().setDate(new Date().getDate() + 28)).toISOString(),
    location: 'Ernakulam, Kerala',
    imageUrl: 'https://picsum.photos/seed/42/600/400',
    imageHint: 'tech conclave',
    organizer: { name: 'NASSCOM Kerala', avatarUrl: 'https://picsum.photos/seed/142/40/40' },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '43',
    title: 'Silent Valley National Park Safari',
    description: 'A jeep safari through the pristine rainforest of Silent Valley.',
    date: new Date(new Date().setDate(new Date().getDate() + 19)).toISOString(),
    location: 'Palakkad, Kerala',
    imageUrl: 'https://picsum.photos/seed/43/600/400',
    imageHint: 'jungle safari',
    organizer: { name: 'Forest Dept.', avatarUrl: 'https://picsum.photos/seed/143/40/40' },
    category: 'Adventure',
    status: 'published',
  },
  {
    id: '44',
    title: 'Kovalam Beach Yoga Retreat',
    description: 'A weekend yoga and meditation retreat at the famous Kovalam beach.',
    date: new Date(new Date().setDate(new Date().getDate() + 17)).toISOString(),
    location: 'Thiruvananthapuram, Kerala',
    imageUrl: 'https://picsum.photos/seed/44/600/400',
    imageHint: 'beach yoga',
    organizer: { name: 'Yoga Waves', avatarUrl: 'https://picsum.photos/seed/144/40/40' },
    category: 'Wellness',
    status: 'published',
  },
  {
    id: '45',
    title: 'Houseboat Building Workshop',
    description: 'Learn the traditional art of building Kettuvallam (houseboats).',
    date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(),
    location: 'Alappuzha, Kerala',
    imageUrl: 'https://picsum.photos/seed/45/600/400',
    imageHint: 'boat building',
    organizer: { name: 'Backwater Artisans', avatarUrl: 'https://picsum.photos/seed/145/40/40' },
    category: 'Workshop',
    status: 'published',
  },
  {
    id: '46',
    title: 'International Film Festival of Kerala (IFFK) Screenings',
    description: 'Screenings of world cinema as part of the IFFK.',
    date: new Date(new Date().setDate(new Date().getDate() + 23)).toISOString(),
    location: 'Thiruvananthapuram, Kerala',
    imageUrl: 'https://picsum.photos/seed/46/600/400',
    imageHint: 'film festival',
    organizer: { name: 'Chalachitra Academy', avatarUrl: 'https://picsum.photos/seed/146/40/40' },
    category: 'Art',
    status: 'published',
  },
  {
    id: '47',
    title: 'Chemmeen Food Fest',
    description: 'A food festival dedicated to prawns, with various preparations.',
    date: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    location: 'Kollam, Kerala',
    imageUrl: 'https://picsum.photos/seed/47/600/400',
    imageHint: 'seafood festival',
    organizer: { name: 'Coastal Flavors', avatarUrl: 'https://picsum.photos/seed/147/40/40' },
    category: 'Food',
    status: 'published',
  },
  {
    id: '48',
    title: 'Edakkal Caves Heritage Walk',
    description: 'A guided walk to the historic Edakkal Caves with ancient petroglyphs.',
    date: new Date(new Date().setDate(new Date().getDate() + 11)).toISOString(),
    location: 'Wayanad, Kerala',
    imageUrl: 'https://picsum.photos/seed/48/600/400',
    imageHint: 'heritage walk',
    organizer: { name: 'Wayanad Heritage Society', avatarUrl: 'https://picsum.photos/seed/148/40/40' },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '49',
    title: 'Mural Painting Workshop',
    description: 'Learn the techniques of traditional Kerala mural painting.',
    date: new Date(new Date().setDate(new Date().getDate() + 13)).toISOString(),
    location: 'Thrissur, Kerala',
    imageUrl: 'https://picsum.photos/seed/49/600/400',
    imageHint: 'painting workshop',
    organizer: { name: 'Chitram', avatarUrl: 'https://picsum.photos/seed/149/40/40' },
    category: 'Art',
    status: 'published',
  },
  {
    id: '50',
    title: 'Kerala Blasters Fan Meetup',
    description: 'A meetup for fans of the Kerala Blasters football team.',
    date: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    location: 'Ernakulam, Kerala',
    imageUrl: 'https://picsum.photos/seed/50/600/400',
    imageHint: 'fan meetup',
    organizer: { name: 'Manjappada', avatarUrl: 'https://picsum.photos/seed/150/40/40' },
    category: 'Sports',
    status: 'published',
  },
  {
    id: '51',
    title: 'Onam Sadya Grand Feast',
    description: 'A grand Onam feast featuring over 26 traditional dishes served on a banana leaf.',
    date: new Date(new Date().setDate(new Date().getDate() + 32)).toISOString(),
    location: 'Kozhikode, Kerala',
    imageUrl: 'https://picsum.photos/seed/51/600/400',
    imageHint: 'traditional feast',
    organizer: { name: 'Onam Celebrations', avatarUrl: 'https://picsum.photos/seed/151/40/40' },
    category: 'Food',
    status: 'published',
  },
  {
    id: '52',
    title: 'Traditional Pottery Workshop',
    description: 'Learn the art of pottery from local artisans in this hands-on workshop.',
    date: new Date(new Date().setDate(new Date().getDate() + 27)).toISOString(),
    location: 'Palakkad, Kerala',
    imageUrl: 'https://picsum.photos/seed/52/600/400',
    imageHint: 'pottery workshop',
    organizer: { name: 'Clay Creators', avatarUrl: 'https://picsum.photos/seed/152/40/40' },
    category: 'Workshop',
    status: 'published',
  },
  {
    id: '53',
    title: 'Bird Watching at Kumarakom',
    description: 'A guided bird watching tour at the famous Kumarakom Bird Sanctuary.',
    date: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    location: 'Kottayam, Kerala',
    imageUrl: 'https://picsum.photos/seed/53/600/400',
    imageHint: 'bird watching',
    organizer: { name: 'Nature Watch', avatarUrl: 'https://picsum.photos/seed/153/40/40' },
    category: 'Adventure',
    status: 'published',
  },
  {
    id: '54',
    title: 'Coconut Handicrafts Fair',
    description: 'An exhibition and sale of beautiful handicrafts made from coconut shells and husks.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    location: 'Malappuram, Kerala',
    imageUrl: 'https://picsum.photos/seed/54/600/400',
    imageHint: 'handicrafts fair',
    organizer: { name: 'Kerala Crafts', avatarUrl: 'https://picsum.photos/seed/154/40/40' },
    category: 'Community',
    status: 'published',
  },
  {
    id: '55',
    title: 'Cycling Tour of Fort Kochi',
    description: 'Explore the historic streets and colonial architecture of Fort Kochi on a bicycle.',
    date: new Date(new Date().setDate(new Date().getDate() + 9)).toISOString(),
    location: 'Ernakulam, Kerala',
    imageUrl: 'https://picsum.photos/seed/55/600/400',
    imageHint: 'cycling tour',
    organizer: { name: 'Kochi Cyclists', avatarUrl: 'https://picsum.photos/seed/155/40/40' },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '56',
    title: 'Thiruvathira Dance Performance',
    description: 'A group performance of the graceful Thiruvathirakali dance to celebrate Onam.',
    date: new Date(new Date().setDate(new Date().getDate() + 31)).toISOString(),
    location: 'Thrissur, Kerala',
    imageUrl: 'https://picsum.photos/seed/56/600/400',
    imageHint: 'folk dance',
    organizer: { name: 'Cultural Group', avatarUrl: 'https://picsum.photos/seed/156/40/40' },
    category: 'Art',
    status: 'published',
  },
  {
    id: '57',
    title: 'Robotics and AI Expo',
    description: 'An expo showcasing the latest innovations in robotics and artificial intelligence from startups.',
    date: new Date(new Date().setDate(new Date().getDate() + 38)).toISOString(),
    location: 'Thiruvananthapuram, Kerala',
    imageUrl: 'https://picsum.photos/seed/57/600/400',
    imageHint: 'robotics expo',
    organizer: { name: 'Future Tech', avatarUrl: 'https://picsum.photos/seed/157/40/40' },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '58',
    title: 'Kayaking in the Arabian Sea',
    description: 'A thrilling sea kayaking adventure along the coast of Kannur.',
    date: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    location: 'Kannur, Kerala',
    imageUrl: 'https://picsum.photos/seed/58/600/400',
    imageHint: 'sea kayaking',
    organizer: { name: 'Coastal Adventures', avatarUrl: 'https://picsum.photos/seed/158/40/40' },
    category: 'Sports',
    status: 'published',
  },
  {
    id: '59',
    title: 'Mindfulness Workshop for Stress Relief',
    description: 'A one-day workshop on mindfulness techniques to manage stress and improve well-being.',
    date: new Date(new Date().setDate(new Date().getDate() + 24)).toISOString(),
    location: 'Alappuzha, Kerala',
    imageUrl: 'https://picsum.photos/seed/59/600/400',
    imageHint: 'mindfulness workshop',
    organizer: { name: 'Calm Minds', avatarUrl: 'https://picsum.photos/seed/159/40/40' },
    category: 'Wellness',
    status: 'published',
  },
  {
    id: '60',
    title: 'Malayalam Poetry Reading',
    description: 'An evening dedicated to the beauty of Malayalam poetry, with readings by contemporary poets.',
    date: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString(),
    location: 'Kollam, Kerala',
    imageUrl: 'https://picsum.photos/seed/60/600/400',
    imageHint: 'poetry reading',
    organizer: { name: 'Kavitha Sargam', avatarUrl: 'https://picsum.photos/seed/160/40/40' },
    category: 'Literature',
    status: 'published',
  },
  {
    id: '61',
    title: 'Ethical Hacking Workshop',
    description: 'A 2-day hands-on workshop on the principles and practices of ethical hacking.',
    date: new Date(new Date().setDate(new Date().getDate() + 42)).toISOString(),
    location: 'Ernakulam, Kerala',
    imageUrl: 'https://picsum.photos/seed/61/600/400',
    imageHint: 'hacking workshop',
    organizer: { name: 'CyberSafe', avatarUrl: 'https://picsum.photos/seed/161/40/40' },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '62',
    title: 'Ramassery Idli Making Class',
    description: 'Learn the secret behind the unique and fluffy Ramassery Idlis.',
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    location: 'Palakkad, Kerala',
    imageUrl: 'https://picsum.photos/seed/62/600/400',
    imageHint: 'cooking class',
    organizer: { name: 'Palakkad Cooks', avatarUrl: 'https://picsum.photos/seed/162/40/40' },
    category: 'Food',
    status: 'published',
  },
  {
    id: '63',
    title: 'Munnar Camping and Stargazing',
    description: 'Camp under the stars in the beautiful hills of Munnar.',
    date: new Date(new Date().setDate(new Date().getDate() + 29)).toISOString(),
    location: 'Idukki, Kerala',
    imageUrl: 'https://picsum.photos/seed/63/600/400',
    imageHint: 'night camping',
    organizer: { name: 'Starry Nights', avatarUrl: 'https://picsum.photos/seed/163/40/40' },
    category: 'Adventure',
    status: 'published',
  },
  {
    id: '64',
    title: 'Local Library Book Drive',
    description: 'Donate your old books and help build a library for the local community.',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    location: 'Kasaragod, Kerala',
    imageUrl: 'https://picsum.photos/seed/64/600/400',
    imageHint: 'book drive',
    organizer: { name: 'Readers for Change', avatarUrl: 'https://picsum.photos/seed/164/40/40' },
    category: 'Community',
    status: 'published',
  },
  {
    id: '65',
    title: 'Gavi Eco-Tourism Tour',
    description: 'An eco-friendly tour of the Gavi forest, promoting sustainable tourism.',
    date: new Date(new Date().setDate(new Date().getDate() + 36)).toISOString(),
    location: 'Pathanamthitta, Kerala',
    imageUrl: 'https://picsum.photos/seed/65/600/400',
    imageHint: 'eco tour',
    organizer: { name: 'Green Getaways', avatarUrl: 'https://picsum.photos/seed/165/40/40' },
    category: 'Travel',
    status: 'published',
  },
  {
    id: '66',
    title: 'Beach Football Tournament',
    description: 'A 5-a-side football tournament on the sandy shores of Kozhikode beach.',
    date: new Date(new Date().setDate(new Date().getDate() + 13)).toISOString(),
    location: 'Kozhikode, Kerala',
    imageUrl: 'https://picsum.photos/seed/66/600/400',
    imageHint: 'beach football',
    organizer: { name: 'Beach Sports', avatarUrl: 'https://picsum.photos/seed/166/40/40' },
    category: 'Sports',
    status: 'published',
  },
  {
    id: '67',
    title: 'Chenda Melam Percussion Ensemble',
    description: 'An electrifying performance by a traditional Chenda Melam percussion ensemble.',
    date: new Date(new Date().setDate(new Date().getDate() + 19)).toISOString(),
    location: 'Thrissur, Kerala',
    imageUrl: 'https://picsum.photos/seed/67/600/400',
    imageHint: 'percussion music',
    organizer: { name: 'Rhythm of Kerala', avatarUrl: 'https://picsum.photos/seed/167/40/40' },
    category: 'Music',
    status: 'published',
  },
  {
    id: '68',
    title: 'Startup Idea Pitching Competition',
    description: 'Pitch your startup idea to a panel of experts and win seed funding.',
    date: new Date(new Date().setDate(new Date().getDate() + 45)).toISOString(),
    location: 'Ernakulam, Kerala',
    imageUrl: 'https://picsum.photos/seed/68/600/400',
    imageHint: 'pitch competition',
    organizer: { name: 'Startup Mission', avatarUrl: 'https://picsum.photos/seed/168/40/40' },
    category: 'Tech',
    status: 'published',
  },
  {
    id: '69',
    title: 'Laughter Yoga Session',
    description: 'A fun and therapeutic session of laughter yoga to boost your mood and health.',
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    location: 'Wayanad, Kerala',
    imageUrl: 'https://picsum.photos/seed/69/600/400',
    imageHint: 'laughter yoga',
    organizer: { name: 'Happy Souls', avatarUrl: 'https://picsum.photos/seed/169/40/40' },
    category: 'Wellness',
    status: 'published',
  },
  {
    id: '70',
    title: 'Short Story Writing Contest',
    description: 'Showcase your storytelling skills in this exciting short story writing competition.',
    date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    location: 'Kottayam, Kerala',
    imageUrl: 'https://picsum.photos/seed/70/600/400',
    imageHint: 'writing contest',
    organizer: { name: 'Katha Junction', avatarUrl: 'https://picsum.photos/seed/170/40/40' },
    category: 'Literature',
    status: 'published',
  },
];
